name: Pytest

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v4
      # Install Python
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      # Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          for FILE in $(find . -name 'requirements.txt'); do
            pip install -r $FILE
          done
      # Run pytest
      - name: Run tests
        run: pytest
      # Write Pytest overview results to a file
      - name: Record test results
        if: '!cancelled()'
        run: |
          [ ! -d .util ] && mkdir -p .util
          [ ! -f .util/pytest_scores.txt ] && touch '.util/pytest_scores.txt'
          pytest -r N --tb=no > .util/pytest_scores.txt || true
      
      - name: Convert scores to json
        if: '!cancelled()'
        run: python .util/parse_raw_python.py --input .util/pytest_scores.txt --output .util/pytest_scores.json --type pytest

      - name: Create badge path directory
        run: |
          [ ! -d .github/badges ] && mkdir -p .github/badges

      - name: Obtain passed_percentage from JSON
        if: '!cancelled()'
        run: |
          echo "PASSED_PERCENTAGE=$(jq '.passed_percentage' .util/pytest_scores.json)" >> $GITHUB_ENV
        env:
          CODE_QUALITY: ${{ env.PASSED_PERCENTAGE }}
          BADGE_PATH: .github/badges/passed_percentage.svg
      - name: Generate the badge SVG image
        uses: emibcn/badge-action@v1
        id: quality_badge
        with:
          label: 'Test Pass:'
          status: ${{ env.PASSED_PERCENTAGE }}
          color: 'blue'
          path: .github/badges/passed_percentage.svg
          scale: 1.5
      - name: Upload badge as artefact
        uses: actions/upload-artifact@v2
        with:
          name: badge
          path: .github/badges/passed_percentage.svg
          if-no-files-found: ignore


      # Commit results
      - name: Push results

        if: '!cancelled()'
        run: |
          git config --local user.email "berkaydur138@gmail.com"
          git config --local user.name "Testing bot"
          git add .util/pytest_scores.txt
          git add .util/pytest_scores.json
          git add .github/badges/passed_percentage.svg
          git commit -m "Update Pytest scores"
          git push