name: Pytest

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v4
      # Install Python
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      # Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          for FILE in $(find . -name 'requirements.txt'); do
            pip install -r $FILE
          done
      # Run pytest
      - name: Run tests
        run: pytest
      # Write Pytest overview results to a file
      - name: Record test results
        if: '!cancelled()'
        run: |
          pytest -r N --tb=no > .util/pytest_scores.txt || true
      # Commit results
      - name: Push results
        if: '!cancelled()'
        run: |
          git config --local user.email "berkaydur138@gmail.com"
          git config --local user.name "Testing bot"
          git add .util/pytest_scores.txt
          git commit -m "Update Pytest scores"
          git push